# 1. Configuracion del entorno

Instalar dependencias

In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn

  Using cached numpy-2.3.2-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached matplotlib-3.10.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached contourpy-1.3.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached kiwisolver-1.4.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
  Using cached pillow-11.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached numpy-2.3.2-cp313-cp313-manylinux_2_27_x86_64.manyli

Importar librerias

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

# 2. Arrays numpy

#### Escalares

In [7]:
escalar = np.array(42)
print("Escalar:", escalar)
print("Tipo de dato:",type(escalar))


print("Tipo de dato del escalar:", escalar.dtype)
print("Dimensiones del escalar:", escalar.ndim)
print("Forma del escalar:", escalar.shape)

Escalar: 42
Tipo de dato: <class 'numpy.ndarray'>
Tipo de dato del escalar: int64
Dimensiones del escalar: 0
Forma del escalar: ()


#### vector

vector con 1 dimencion

In [9]:
vector = np.array([40,45, 30, 23, 15, 36, 42])
print("Vector:", vector)


print("Tipo de dato del vector:", vector.dtype)
print("Dimensiones del vector:", vector.ndim)
print("Forma del vector:", vector.shape)
print("Elemento en la posición 2 del vector:", vector[2])

Vector: [40 45 30 23 15 36 42]
Tipo de dato del vector: int64
Dimensiones del vector: 1
Forma del vector: (7,)
Elemento en la posición 2 del vector: 30


#### Matriz

matriz de 3 dimenciones

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:\n", matrix)

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Tensor

matriz de 4 dimenciones

In [11]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## creacion de arrays

NumPy ofrece diversas formas para crear arrays, cada una adaptándose a situaciones específicas:

- Conversión desde otras estructuras de Python, como listas y tuplas.
- Funciones de creación, como `np.zeros` para matrices de ceros.
- Replicación, unión o mutación de arrays existentes.
- Lectura de arrays desde disco, en formatos estándar o personalizados.
- Creación desde bytes crudos usando cadenas o buffers.
- Funciones especiales de bibliotecas de álgebra lineal.

Veamos un ejemplo usando `arange`:

In [14]:
array_arange = np.arange(0, 12, 2)
print("Array creado con arange:", array_arange)

array_zeros = np.zeros((3, 4))
print("Array de ceros:\n", array_zeros)

Array creado con arange: [ 0  2  4  6  8 10]
Array de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


matriz de identidad

In [16]:
eye_matrix = np.eye(4)
print("Matriz identidad:\n", eye_matrix)

eye_matrix = np.eye(6)
print("Matriz identidad 6x6:\n", eye_matrix)

Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz identidad 6x6:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


matriz diagonal

In [17]:
diagonal_matrix = np.diag([1, 2, 3, 4])
print("Matriz diagonal:\n", diagonal_matrix)

Matriz diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


matriz aleatoria

In [23]:
random_matrix = np.random.rand(3, 3)
print("Matriz aleatoria 4x4:\n", random_matrix)

random_matrix = np.random.randint(1, 6, size=(3, 3))
print("Matriz aleatoria 3x3:\n", random_matrix)



Matriz aleatoria 4x4:
 [[0.79478213 0.85675131 0.45540242]
 [0.03556282 0.42961071 0.16610629]
 [0.30573717 0.98250052 0.08010246]]
Matriz aleatoria 3x3:
 [[4 1 2]
 [2 3 3]
 [5 5 2]]


# 3. Manipulación de Arrays NumPy 

#### atributos del array

In [24]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print("Dimensiones:", array.ndim)
print("Forma:", array.shape)
print("Tipo de dato:", array.dtype)


print("Tamaño (número de elementos):", array.size)
print("Tamaño en bytes de cada elemento:", array.itemsize)
print("Tamaño total en bytes del array:", array.nbytes)

[[1 2 3]
 [4 5 6]]
Dimensiones: 2
Forma: (2, 3)
Tipo de dato: int64
Tamaño (número de elementos): 6
Tamaño en bytes de cada elemento: 8
Tamaño total en bytes del array: 48


#### Especificando Tipos de Datos (Datatypes)

Al crear un array, podemos especificar el tipo de datos que contendrá utilizando el parámetro `dtype`. Esta especificación es crucial para la eficiencia y precisión en cálculos numéricos. Aquí se detallan algunos de los tipos de datos más comunes:

- `int32`: Entero de 32 bits.
- `float32`: Número de punto flotante de 32 bits.
- `float64`: Número de punto flotante de 64 bits (por defecto para números flotantes en NumPy).
- `bool`: Valores booleanos (True o False).
- `complex64`: Número complejo de 64 bits.
- `complex128`: Número complejo de 128 bits.
- `str`: Cadenas de texto.


Podemos especificar estos tipos de datos al crear el array utilizando el parámetro `dtype`:

In [25]:
z = np.array(3, dtype=np.uint8)
print("Array z:", z)
print("Tipo de dato de z:", z.dtype)

Array z: 3
Tipo de dato de z: uint8


especificar el tipo de dato

In [ ]:
double_array = np.array([1, 2, 3], dtype=np.float64)
print("Array de tipo float64:", double_array)
print("Tipo de dato:", double_array.dtype)

double_array = np.array([1, 2, 3], dtype='double')
print("Array de tipo int32:", double_array)
print("Tipo de dato:", double_array.dtype)

double_array = np.array([1, 2, 3], dtype='d')
print("Array de tipo float64:", double_array)
print("Tipo de dato:", double_array.dtype)


Array de tipo float64: [1. 2. 3.]
Tipo de dato: float64
Array de tipo float64: [1. 2. 3.]
Tipo de dato: float64
Array de tipo int32: [1. 2. 3.]
Tipo de dato: float64


coversion de tipo con astype

In [29]:
z = z.astype(np.float32)
print("Array z después de convertir a float32:", z)
print("Tipo de dato de z después de la conversión:", z.dtype)

Array z después de convertir a float32: 3.0
Tipo de dato de z después de la conversión: float32


notaciones con numpy

suma

In [30]:
array = np.array([[1, 2, 3], [4, 5, 6]])
sum = np.sum(array)
print("Suma de todos los elementos del array:", sum)

Suma de todos los elementos del array: 21


media

In [31]:
mean = np.mean(array)
print("Media de todos los elementos del array:", mean)

Media de todos los elementos del array: 3.5


desviacion estandar

In [32]:
std = np.std(array)
print("Desviación estándar de todos los elementos del array:", std)

Desviación estándar de todos los elementos del array: 1.707825127659933


In [35]:
arrayA = np.array([[1, 2], [3, 4]])
print("Array A:\n", arrayA)
arrayB = np.array([[5, 6], [7, 8]])
print("Array B:\n", arrayB)
sum_arrays = arrayA + arrayB
print("Suma de dos arrays:\n", sum_arrays)
product_arrays = arrayA * arrayB
print("Producto de dos arrays:\n", product_arrays)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Suma de dos arrays:
 [[ 6  8]
 [10 12]]
Producto de dos arrays:
 [[ 5 12]
 [21 32]]


# 5. indexación y Slicing en Numpy

In [39]:
array = np.array([10, 20, 30, 40, 50])
print("Array original:\n", array)
print("Segundo elemento del array:",array[1])
print("Ultimo elemnto del array:",array[-1])

Array original:
 [10 20 30 40 50]
Segundo elemento del array: 20
Ultimo elemnto del array: 50
